apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"cronjobrunner","namespace":"devops"}}
  creationTimestamp: "2020-07-14T19:57:46Z"
  name: cronjobrunner
  namespace: devops
  resourceVersion: "5936211"
  selfLink: /api/v1/namespaces/devops/serviceaccounts/cronjobrunner
  uid: a2062405-8ac7-489c-a74e-934802ca715e
secrets:
- name: cronjobrunner-token-lpcnh
