apiVersion: v1
kind: Service
metadata:
  labels:
    app: cm-manager
  name: cm-manager
  namespace: devops
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: cm-manager
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 2
  name: devops-cm-manager
  namespace: devops
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cm-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cm-manager
      name: devops-cm-manager
      namespace: devops
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - ${ADMIN_POOL}
      containers:
      - image: gcr.io/pr-ca-merch/configmap-manager:1.0.1
        imagePullPolicy: IfNotPresent
        name: cm-manager
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: jenkins
      serviceAccountName: jenkins
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: camerchrole
        operator: Equal
        value: admin
