apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":null,"name":"cronjubrunner","namespace":"devops"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"cronjubrunner"}},"strategy":{"rollingUpdate":{"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"annotations":null,"labels":{"app":"cronjubrunner"},"name":"cronjubrunner","namespace":"devops"},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"cloud.google.com/gke-nodepool","operator":"In","values":["default-gke-pool-dev"]}]}]}}},"containers":[{"env":[{"name":"PUBSUB_SUBSCRIPTION_TO_DEF","value":"projects/np-ca-merch/subscriptions/k8scronjbos"}],"image":"gcr.io/np-ca-merch/job-executor:1.1.0","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":"http"},"initialDelaySeconds":15,"periodSeconds":60,"successThreshold":1,"timeoutSeconds":1},"name":"cronjobrunner","ports":[{"containerPort":8080,"name":"http"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":"http"},"initialDelaySeconds":5,"periodSeconds":60,"successThreshold":1,"timeoutSeconds":1}}],"securityContext":{"fsGroup":1000},"serviceAccountName":"cronjobrunner","tolerations":[{"key":"thdcarole","operator":"Equal","value":"admin_qa"}]}}}}
  creationTimestamp: "2020-07-14T19:57:46Z"
  generation: 1
  name: cronjubrunner
  namespace: devops
  resourceVersion: "35794474"
  selfLink: /apis/apps/v1/namespaces/devops/deployments/cronjubrunner
  uid: 9c1dda05-73b4-44a1-87dd-816d0d97fd28
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cronjubrunner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cronjubrunner
      name: cronjubrunner
      namespace: devops
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - ${DEFAULT_POOL} 
      containers:
      - env:
        - name: PUBSUB_SUBSCRIPTION_TO_DEF
          value: projects/pr-ca-merch/subscriptions/k8scronjbos
        image: gcr.io/pr-ca-merch/job-executor:1.1.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        name: cronjobrunner
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      serviceAccount: cronjobrunner
      serviceAccountName: cronjobrunner
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: thdcarole
        operator: Equal
        value: admin_qa
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-07-14T19:57:46Z"
    lastUpdateTime: "2020-07-14T19:58:35Z"
    message: ReplicaSet "cronjubrunner-759895fd7b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-09-11T18:26:59Z"
    lastUpdateTime: "2020-09-11T18:26:59Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
