apiVersion: v1
kind: Service
metadata:
  labels:
    app: dbconsole
  name: dbconsole
  namespace: devops
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: dbconsole
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: null
  name: devops-dbconsole
  namespace: devops
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dbconsole
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        app: dbconsole
      name: devops-dbconsole
      namespace: devops
    spec:
      containers:
      - env:
        - name: PMA_ARBITRARY
          value: '1'
        image: phpmyadmin/phpmyadmin:4.7
        name: dbconsole
        ports:
        - containerPort: 80
          name: http
