apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":null,"name":"devops-pgadmin","namespace":"devops"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"pgadmin"}},"strategy":{"rollingUpdate":{"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{},"labels":{"app":"pgadmin"},"name":"devops-pgadmin","namespace":"devops"},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"cloud.google.com/gke-nodepool","operator":"In","values":["admin-gke-pool-dev"]}]}]}}},"containers":[{"command":["sh","-c","sed -ie 's/ True/ False/' /pgadmin4/config.py  \u0026\u0026 sed -ie 's/paranoid = /#paranoid = /' /pgadmin4/pgadmin/__init__.py  \u0026\u0026 sed -ie 's/paranoid.redirect_view =/x =/' /pgadmin4/pgadmin/__init__.py     \u0026\u0026  /entrypoint.sh "],"env":[{"name":"PGADMIN_DEFAULT_EMAIL","valueFrom":{"secretKeyRef":{"key":"username","name":"pgadmin"}}},{"name":"PGADMIN_DEFAULT_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"pgadmin"}}},{"name":"PGADMIN_PORT","value":"80"},{"name":"TZ","value":"America/Toronto"},{"name":"PGADMIN_SESSION_DISK_WRITE_DELAY","value":"0"}],"image":"dpage/pgadmin4:4.15","name":"pgadmin","ports":[{"containerPort":80,"name":"http"}]}],"securityContext":{"fsGroup":1000},"tolerations":[{"key":"camerchrole","operator":"Equal","value":"admin"}]}}}}
  creationTimestamp: "2020-07-08T05:12:42Z"
  generation: 4
  name: devops-pgadmin
  namespace: devops
  resourceVersion: "2672278"
  selfLink: /apis/apps/v1/namespaces/devops/deployments/devops-pgadmin
  uid: ad44a108-5dca-4498-9aca-ee05b9d508b3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pgadmin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pgadmin
      name: devops-pgadmin
      namespace: devops
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - ${ADMIN_POOL} 
      containers:
      - command:
        - sh
        - -c
        - 'sed -ie ''s/ True/ False/'' /pgadmin4/config.py  && sed -ie ''s/paranoid
          = /#paranoid = /'' /pgadmin4/pgadmin/__init__.py  && sed -ie ''s/paranoid.redirect_view
          =/x =/'' /pgadmin4/pgadmin/__init__.py     &&  /entrypoint.sh '
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              key: username
              name: pgadmin
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pgadmin
        - name: PGADMIN_PORT
          value: "80"
        - name: TZ
          value: America/Toronto
        - name: PGADMIN_SESSION_DISK_WRITE_DELAY
          value: "0"
        image: dpage/pgadmin4:4.15
        imagePullPolicy: IfNotPresent
        name: pgadmin
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: camerchrole
        operator: Equal
        value: admin
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-07-08T05:16:17Z"
    lastUpdateTime: "2020-07-08T05:16:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-07-08T05:54:31Z"
    lastUpdateTime: "2020-07-08T05:54:42Z"
    message: ReplicaSet "devops-pgadmin-5d9fcdcbd8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
