apiVersion: v1
kind: Service
metadata:
  labels:
    service: log-server
  name: log-server
  namespace: kong
spec:
  ports:
  - name: log-server
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: log-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-server
  namespace: kong
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-server
      name: log-server
  template:
    metadata:
      labels:
        app: log-server
        name: log-server
    spec:
      containers:
      - image: gcr.io/pr-ca-merch/log-server:2.1.0
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: log-server
        ports:
        - containerPort: 8080
          name: log-server
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            memory: 300Mi
          requests:
            memory: 100Mi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kong-logserver-hpa
  namespace: kong
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: log-server
  targetCPUUtilizationPercentage: 80
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kong-log-server-pdb
  namespace: kong
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: log-server
