apiVersion: v1
kind: Service
metadata:
  labels:
    app: chartmuseum
    chart: chartmuseum-2.1.0
    heritage: Tiller
    release: release-name
  name: release-name-chartmuseum
  namespace: devops
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: chartmuseum
    release: release-name
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: chartmuseum
    chart: chartmuseum-2.1.0
    heritage: Tiller
    release: release-name
  name: release-name-chartmuseum
  namespace: devops
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: chartmuseum
      release: release-name
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        app: chartmuseum
        release: release-name
      name: release-name-chartmuseum
      namespace: devops
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - ${ADMIN_POOL}
      containers:
      - args:
        - --port=8080
        env:
        - name: AUTH_ANONYMOUS_GET
          value: 'true'
        - name: CHART_POST_FORM_FIELD_NAME
          value: chart
        - name: DISABLE_API
          value: 'false'
        - name: DISABLE_METRICS
          value: 'true'
        - name: LOG_JSON
          value: 'true'
        - name: PROV_POST_FORM_FIELD_NAME
          value: prov
        - name: STORAGE
          value: google
        - name: STORAGE_GOOGLE_BUCKET
          value: np-ca-merch-chart-museum
        - name: STORAGE_GOOGLE_PREFIX
          value: ''
        - name: BASIC_AUTH_PASS
          valueFrom:
            secretKeyRef:
              key: password
              name: museum
        - name: BASIC_AUTH_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: museum
        image: chartmuseum/chartmuseum:v0.8.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: chartmuseum
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      securityContext:
        fsGroup: 1000
      tolerations:
      - key: camerchrole
        operator: Equal
        value: admin
      volumes:
      - emptyDir: {}
        name: storage-volume
