apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":null,"name":"devops-redisconsole","namespace":"devops"},"spec":{"replicas":1,"revisionHistoryLimit":10,"strategy":{"rollingUpdate":{"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{},"labels":{"app":"redisconsole"},"name":"devops-redisconsole","namespace":"devops"},"spec":{"containers":[{"image":"gcr.io/np-ca-merch/redis-console:1.0.1","name":"redisconsole","ports":[{"containerPort":5001,"name":"http"}]}]}}}}
  creationTimestamp: "2019-09-27T15:42:24Z"
  generation: 1
  labels:
    app: redisconsole
  name: devops-redisconsole
  namespace: devops
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redisconsole
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redisconsole
      name: devops-redisconsole
      namespace: devops
    spec:
      containers:
      - image: gcr.io/pr-ca-merch/redis-console:1.0.1
        imagePullPolicy: IfNotPresent
        name: redisconsole
        ports:
        - containerPort: 5001
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redisconsole
  name: redisconsole
  namespace: devops
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: redisconsole
  sessionAffinity: None
  type: ClusterIP
